<?php
include("./View/HeadAndBG.php");
include("./View/Header/commonVisitorHeader.php");
include("./View/search-tab.php");
include("./View/search-result.php");
include("./View/loan.php");
include("./View/login.php");
include("./View/footer.php");
?>